### ISSUE TITLE
Add `awesome` and `awesome-list` as GitHub repository topics.

### ISSUE THREAD

**Issue by fabacab** [ajvb/awesome-tor#6]
The latest style guide for Awesome Lists requires the addition of the `awesome` and `awesome-list` [GitHub repository topics](https://help.github.com/articles/about-topics/). These are currently missing from this repository.

**Comment by fabacab** [comment]
Ping @ajvb. Sorry to bug you about this, but managing repository topics is only something a repository owner (not a collaborator) can do, AFAIK. Should be a two-second task! :)

**Comment by ajvb** [comment]
Added!
